/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tech.adrianohrl.identistry.view.panels;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ButtonModel;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;
import org.apache.log4j.Logger;
import tech.adrianohrl.identistry.model.individuals.Address;
import tech.adrianohrl.identistry.model.individuals.AddressUtil;
import tech.adrianohrl.identistry.model.individuals.Genders;
import tech.adrianohrl.identistry.view.components.ImageUtil;

/**
 *
 * @author adrianohrl
 */
public class PersonPanel extends javax.swing.JPanel implements WizardPagePanel {
    
    private static final Logger logger = Logger.getLogger(PersonPanel.class);

    /**
     * Creates new form NewPersonPanel
     */
    public PersonPanel() {
        initComponents();
    }
    
    public String getPersonName() {
        return nameTextField.getText();
    }
    
    public ImageIcon getPersonProfilePicture() {
        return (ImageIcon) pictureLabel.getIcon();
    }
    
    public Genders getPersonGender() {
        ButtonModel radioButton = genderButtonGroup.getSelection();
        return radioButton != null ? Genders.getInstance(radioButton.getActionCommand()) : null;
    }
    
    public Calendar getPersonDayOfBirth() {
        if (dobFormattedTextField.getText().isEmpty()) {
            return null;
        }
        Calendar dob = Calendar.getInstance();
        dob.setTime((Date) dobFormattedTextField.getValue());
        return dob;
    }
    
    public String getPersonPhone() {
        return phoneFormattedTextField.getText();
    }
    
    public boolean getPersonPhoneWhatsApp() {
        return whatsappCheckBox.isSelected();
    }
    
    public String getPersonCPF() {
        return cpfFormattedTextField.getText();
    }
    
    public String getPersonRG() {
        return rgTextField.getText();
    }
    
    public Address getPersonAddress() {
        String street = streetTextField.getText();
        int number = (int) numberFormattedTextField.getValue();
        String obs = obsTextField.getText();
        String area = areaTextField.getText();
        String zip = zipFormattedTextField.getText();
        String city = (String) cityComboBox.getSelectedItem();
        String state = (String) stateComboBox.getSelectedItem();
        return new Address(street, number, area, obs, zip, city, state, "Brasil");
    }
    
    public String getPersonFacebook() {
        return facebookLabel.getText() + facebookTextField.getText();
    }
    
    public String getPersonInstagram() {
        return instagramLabel.getText() + instagramTextField.getText();
    }
    
    public String getPersonOccupation() {
        return occupationTextField.getText();
    }
    
    private boolean isAddressFilled() {
        Address address = getPersonAddress();
        return !address.getStreet().isEmpty()
            && address.getNumber() > 0
            && !address.getArea().isEmpty()
            && !address.getCity().isEmpty()
            && !address.getUf().isEmpty()
            && !address.getCountry().isEmpty();
    }
            
    @Override
    public boolean isFilled() {
        return !getPersonName().isEmpty() 
            && getPersonGender() != null
            && getPersonDayOfBirth() != null
            && !getPersonPhone().isEmpty()
            //&& !getPersonCPF().isEmpty()
            && !getPersonRG().isEmpty()
            && isAddressFilled()
            && getPersonProfilePicture() != null;
    }

    @Override
    public Component getFirstFocusableComponent() {
        return nameTextField;
    }

    @Override
    public void setLastFocusableComponent(Component component) {
        pictureLabel.setNextFocusableComponent(component);
    }
    
    private ComboBoxModel getStates() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("");
        for (String state : AddressUtil.getStates()) {
            model.addElement(state);
        }
        model.setSelectedItem("");
        return model;
    }
    
    private ComboBoxModel getCities(String state) {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("");
        for (String city : AddressUtil.getStateCities(state)) {
            model.addElement(city);
        }
        model.setSelectedItem("");
        return model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        personPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        genderPanel = new javax.swing.JPanel();
        genderFemaleRadioButton = new javax.swing.JRadioButton();
        genderMaleRadioButton = new javax.swing.JRadioButton();
        dobFormattedTextField = new javax.swing.JFormattedTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneFormattedTextField = new javax.swing.JFormattedTextField();
        whatsappLabelIcon = new javax.swing.JLabel();
        whatsappLabel = new javax.swing.JLabel();
        whatsappCheckBox = new javax.swing.JCheckBox();
        rgLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        rgTextField = new javax.swing.JTextField();
        cpfFormattedTextField = new javax.swing.JFormattedTextField();
        dobLabel = new javax.swing.JLabel();
        addressPanel = new javax.swing.JPanel();
        streetLabel = new javax.swing.JLabel();
        streetTextField = new javax.swing.JTextField();
        numberLabel = new javax.swing.JLabel();
        numberFormattedTextField = new javax.swing.JFormattedTextField();
        areaLabel = new javax.swing.JLabel();
        areaTextField = new javax.swing.JTextField();
        obsLabel = new javax.swing.JLabel();
        obsTextField = new javax.swing.JTextField();
        zipLabel = new javax.swing.JLabel();
        zipFormattedTextField = new javax.swing.JFormattedTextField();
        stateLabel = new javax.swing.JLabel();
        stateComboBox = new javax.swing.JComboBox();
        cityLabel = new javax.swing.JLabel();
        cityComboBox = new javax.swing.JComboBox();
        picturePanel = new javax.swing.JPanel();
        pictureLabel = new javax.swing.JLabel();
        socialNetworksPanel = new javax.swing.JPanel();
        facebookLabelIcon = new javax.swing.JLabel();
        facebookLabel = new javax.swing.JLabel();
        instagramLabel = new javax.swing.JLabel();
        facebookLabel1 = new javax.swing.JLabel();
        facebookTextField = new javax.swing.JTextField();
        intagramLabelIcon = new javax.swing.JLabel();
        instagramLabel1 = new javax.swing.JLabel();
        instagramTextField = new javax.swing.JTextField();
        occupationLabel = new javax.swing.JLabel();
        occupationTextField = new javax.swing.JTextField();

        genderButtonGroup.add(genderFemaleRadioButton);
        genderButtonGroup.add(genderMaleRadioButton);

        setNextFocusableComponent(nameTextField);

        personPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Data"));

        nameLabel.setLabelFor(nameTextField);
        nameLabel.setText("Name *:");
        nameLabel.setFocusable(false);

        nameTextField.setToolTipText("Enter the name.");
        nameTextField.setNextFocusableComponent(genderFemaleRadioButton);

        genderLabel.setLabelFor(genderPanel);
        genderLabel.setText("Gender *:");
        genderLabel.setFocusable(false);

        genderPanel.setToolTipText("Select the gender.");
        genderPanel.setMaximumSize(new java.awt.Dimension(20, 100));
        genderPanel.setMinimumSize(new java.awt.Dimension(20, 22));

        genderFemaleRadioButton.setText("Female");
        genderFemaleRadioButton.setNextFocusableComponent(genderMaleRadioButton);

        genderMaleRadioButton.setText("Male");
        genderMaleRadioButton.setNextFocusableComponent(dobFormattedTextField);

        javax.swing.GroupLayout genderPanelLayout = new javax.swing.GroupLayout(genderPanel);
        genderPanel.setLayout(genderPanelLayout);
        genderPanelLayout.setHorizontalGroup(
            genderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genderPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(genderFemaleRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genderMaleRadioButton)
                .addContainerGap())
        );
        genderPanelLayout.setVerticalGroup(
            genderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(genderMaleRadioButton)
                .addComponent(genderFemaleRadioButton))
        );

        dobFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        dobFormattedTextField.setToolTipText("Enter the day-of-birth.");
        dobFormattedTextField.setNextFocusableComponent(phoneFormattedTextField);

        phoneLabel.setText("Phone *:");
        phoneLabel.setFocusable(false);

        try {
            phoneFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phoneFormattedTextField.setToolTipText("Enter the phone number.");
        phoneFormattedTextField.setNextFocusableComponent(whatsappCheckBox);

        whatsappLabelIcon.setIcon(IconFontSwing.buildIcon(FontAwesome.WHATSAPP, 20));
        whatsappLabelIcon.setLabelFor(whatsappCheckBox);
        whatsappLabelIcon.setMaximumSize(new java.awt.Dimension(21, 21));
        whatsappLabelIcon.setMinimumSize(new java.awt.Dimension(21, 21));
        whatsappLabelIcon.setPreferredSize(new java.awt.Dimension(21, 21));

        whatsappLabel.setText(":");

        whatsappCheckBox.setToolTipText("Select if the associated phone number has WhatsApp.");
        whatsappCheckBox.setNextFocusableComponent(cpfFormattedTextField);

        rgLabel.setLabelFor(rgTextField);
        rgLabel.setText("RG *:");
        rgLabel.setFocusable(false);

        cpfLabel.setLabelFor(cpfFormattedTextField);
        cpfLabel.setText("CPF:");
        cpfLabel.setFocusable(false);

        rgTextField.setToolTipText("Enter the RG number.");
        rgTextField.setNextFocusableComponent(streetTextField);

        try {
            cpfFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfFormattedTextField.setToolTipText("Enter the CPF number.");
        cpfFormattedTextField.setNextFocusableComponent(rgTextField);

        dobLabel.setLabelFor(dobFormattedTextField);
        dobLabel.setText("Day of Birth *:");
        dobLabel.setFocusable(false);

        javax.swing.GroupLayout personPanelLayout = new javax.swing.GroupLayout(personPanel);
        personPanel.setLayout(personPanelLayout);
        personPanelLayout.setHorizontalGroup(
            personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genderLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dobLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cpfLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(personPanelLayout.createSequentialGroup()
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(genderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobFormattedTextField)
                            .addComponent(cpfFormattedTextField))
                        .addGap(18, 18, 18)
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rgLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(personPanelLayout.createSequentialGroup()
                                .addComponent(phoneFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(whatsappLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(whatsappLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(whatsappCheckBox))))
                    .addComponent(nameTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        personPanelLayout.setVerticalGroup(
            personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(genderLabel)
                    .addComponent(genderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(whatsappLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whatsappLabel)
                    .addComponent(whatsappCheckBox)
                    .addComponent(phoneFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel)
                    .addComponent(dobFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cpfLabel)
                    .addComponent(cpfFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgLabel)
                    .addComponent(rgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        addressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));

        streetLabel.setLabelFor(streetTextField);
        streetLabel.setText("Street *:");
        streetLabel.setFocusable(false);

        streetTextField.setToolTipText("Enter the street name.");
        streetTextField.setNextFocusableComponent(numberFormattedTextField);

        numberLabel.setLabelFor(numberFormattedTextField);
        numberLabel.setText("Number *:");
        numberLabel.setFocusable(false);

        numberFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        numberFormattedTextField.setToolTipText("Enter the house number.");
        numberFormattedTextField.setNextFocusableComponent(obsTextField);

        areaLabel.setLabelFor(areaTextField);
        areaLabel.setText("Area *:");
        areaLabel.setFocusable(false);

        areaTextField.setToolTipText("Enter the city area name.");
        areaTextField.setNextFocusableComponent(zipFormattedTextField);

        obsLabel.setLabelFor(obsTextField);
        obsLabel.setText("Observation:");
        obsLabel.setFocusable(false);

        obsTextField.setToolTipText("Enter additional informations about the address.");
        obsTextField.setNextFocusableComponent(areaTextField);

        zipLabel.setLabelFor(zipFormattedTextField);
        zipLabel.setText("ZIP Code:");
        zipLabel.setFocusable(false);

        try {
            zipFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        zipFormattedTextField.setToolTipText("Enter the address ZIP code.");
        zipFormattedTextField.setNextFocusableComponent(stateComboBox);

        stateLabel.setLabelFor(stateComboBox);
        stateLabel.setText("State *:");
        stateLabel.setFocusable(false);

        stateComboBox.setModel(getStates());
        stateComboBox.setToolTipText("Select the state name.");
        stateComboBox.setNextFocusableComponent(cityComboBox);
        stateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateComboBoxActionPerformed(evt);
            }
        });

        cityLabel.setLabelFor(cityComboBox);
        cityLabel.setText("City *:");
        cityLabel.setFocusable(false);

        cityComboBox.setToolTipText("Enter the city name.");
        cityComboBox.setEnabled(false);
        cityComboBox.setNextFocusableComponent(facebookTextField);

        javax.swing.GroupLayout addressPanelLayout = new javax.swing.GroupLayout(addressPanel);
        addressPanel.setLayout(addressPanelLayout);
        addressPanelLayout.setHorizontalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zipLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(obsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(streetLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addressPanelLayout.createSequentialGroup()
                        .addComponent(zipFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(obsTextField)
                    .addComponent(streetTextField))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(areaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numberLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cityLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numberFormattedTextField)
                    .addComponent(areaTextField)
                    .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        addressPanelLayout.setVerticalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(streetLabel)
                    .addComponent(streetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberLabel)
                    .addComponent(numberFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(obsLabel)
                    .addComponent(obsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaLabel)
                    .addComponent(areaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(zipLabel)
                    .addComponent(zipFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLabel)
                    .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityLabel)
                    .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        picturePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Picture"));

        pictureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no-picture/128x128.png"))); // NOI18N
        pictureLabel.setToolTipText("Alter profile picture");
        pictureLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pictureLabelMouseClicked(evt);
            }
        });
        pictureLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pictureLabelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout picturePanelLayout = new javax.swing.GroupLayout(picturePanel);
        picturePanel.setLayout(picturePanelLayout);
        picturePanelLayout.setHorizontalGroup(
            picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(picturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureLabel)
                .addContainerGap())
        );
        picturePanelLayout.setVerticalGroup(
            picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(picturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureLabel)
                .addContainerGap())
        );

        socialNetworksPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Social Networks"));

        facebookLabelIcon.setIcon(IconFontSwing.buildIcon(FontAwesome.FACEBOOK_OFFICIAL, 20));
        facebookLabelIcon.setLabelFor(facebookTextField);
        facebookLabelIcon.setMaximumSize(new java.awt.Dimension(21, 21));
        facebookLabelIcon.setMinimumSize(new java.awt.Dimension(21, 21));
        facebookLabelIcon.setPreferredSize(new java.awt.Dimension(21, 21));

        facebookLabel.setText("https://facebook.com/");

        instagramLabel.setText("https://instagram.com/");

        facebookLabel1.setText(":");

        facebookTextField.setNextFocusableComponent(instagramTextField);

        intagramLabelIcon.setIcon(IconFontSwing.buildIcon(FontAwesome.INSTAGRAM, 20));
        intagramLabelIcon.setLabelFor(instagramTextField);
        intagramLabelIcon.setMaximumSize(new java.awt.Dimension(21, 21));
        intagramLabelIcon.setMinimumSize(new java.awt.Dimension(21, 21));
        intagramLabelIcon.setPreferredSize(new java.awt.Dimension(21, 21));

        instagramLabel1.setText(":");

        instagramTextField.setNextFocusableComponent(occupationTextField);

        occupationLabel.setText("Occupation:");

        occupationTextField.setNextFocusableComponent(pictureLabel);

        javax.swing.GroupLayout socialNetworksPanelLayout = new javax.swing.GroupLayout(socialNetworksPanel);
        socialNetworksPanel.setLayout(socialNetworksPanelLayout);
        socialNetworksPanelLayout.setHorizontalGroup(
            socialNetworksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(socialNetworksPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(socialNetworksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(occupationLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, socialNetworksPanelLayout.createSequentialGroup()
                        .addComponent(intagramLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(instagramLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, socialNetworksPanelLayout.createSequentialGroup()
                        .addComponent(facebookLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(facebookLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(socialNetworksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(occupationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(socialNetworksPanelLayout.createSequentialGroup()
                        .addComponent(facebookLabel)
                        .addGap(0, 0, 0)
                        .addComponent(facebookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(socialNetworksPanelLayout.createSequentialGroup()
                        .addComponent(instagramLabel)
                        .addGap(0, 0, 0)
                        .addComponent(instagramTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        socialNetworksPanelLayout.setVerticalGroup(
            socialNetworksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(socialNetworksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(socialNetworksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(facebookLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facebookLabel1)
                    .addComponent(facebookLabel)
                    .addComponent(facebookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(socialNetworksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(intagramLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instagramLabel1)
                    .addComponent(instagramLabel)
                    .addComponent(instagramTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(socialNetworksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(occupationLabel)
                    .addComponent(occupationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(personPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 72, Short.MAX_VALUE)
                        .addComponent(picturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(socialNetworksPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(personPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(socialNetworksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {personPanel, picturePanel});

    }// </editor-fold>//GEN-END:initComponents

    private void pictureLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pictureLabelMouseClicked
        ImageIcon icon = ImageUtil.chooseImageIcon(this);
        if (icon != null) {
            pictureLabel.setIcon(icon);
        }        
    }//GEN-LAST:event_pictureLabelMouseClicked

    private void pictureLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pictureLabelKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            System.out.println("Space key pressed over the picture label...");
            ImageIcon icon = ImageUtil.chooseImageIcon(this);
            if (icon != null) {
                pictureLabel.setIcon(icon);
            }  
        }
    }//GEN-LAST:event_pictureLabelKeyPressed

    private void stateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateComboBoxActionPerformed
        String state = (String) stateComboBox.getSelectedItem();
        if (!AddressUtil.isValid(state)) {
            stateComboBox.setSelectedItem("");
            cityComboBox.setSelectedItem("");
            cityComboBox.setEnabled(false);
            return;
        }
        System.out.println("State selected: " + state);
        cityComboBox.setModel(getCities(state));
        cityComboBox.setSelectedItem("");
        cityComboBox.setEnabled(true);
    }//GEN-LAST:event_stateComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addressPanel;
    private javax.swing.JLabel areaLabel;
    private javax.swing.JTextField areaTextField;
    private javax.swing.JComboBox cityComboBox;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JFormattedTextField cpfFormattedTextField;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JFormattedTextField dobFormattedTextField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel facebookLabel;
    private javax.swing.JLabel facebookLabel1;
    private javax.swing.JLabel facebookLabelIcon;
    private javax.swing.JTextField facebookTextField;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JRadioButton genderFemaleRadioButton;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JRadioButton genderMaleRadioButton;
    private javax.swing.JPanel genderPanel;
    private javax.swing.JLabel instagramLabel;
    private javax.swing.JLabel instagramLabel1;
    private javax.swing.JTextField instagramTextField;
    private javax.swing.JLabel intagramLabelIcon;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JFormattedTextField numberFormattedTextField;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel obsLabel;
    private javax.swing.JTextField obsTextField;
    private javax.swing.JLabel occupationLabel;
    private javax.swing.JTextField occupationTextField;
    private javax.swing.JPanel personPanel;
    private javax.swing.JFormattedTextField phoneFormattedTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JPanel picturePanel;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JTextField rgTextField;
    private javax.swing.JPanel socialNetworksPanel;
    private javax.swing.JComboBox stateComboBox;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField streetTextField;
    private javax.swing.JCheckBox whatsappCheckBox;
    private javax.swing.JLabel whatsappLabel;
    private javax.swing.JLabel whatsappLabelIcon;
    private javax.swing.JFormattedTextField zipFormattedTextField;
    private javax.swing.JLabel zipLabel;
    // End of variables declaration//GEN-END:variables

}
